// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBierfXGriDzTYB61VEgYjC7o991hi3uds',
    appId: '1:725078999508:web:ebacb0d48949b36c935641',
    messagingSenderId: '725078999508',
    projectId: 'fixitapp-a6733',
    authDomain: 'fixitapp-a6733.firebaseapp.com',
    storageBucket: 'fixitapp-a6733.firebasestorage.app',
    measurementId: 'G-SL526V4GJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTzqJJGYwk_6GIG0CNyYU3RyTRpXty4eY',
    appId: '1:725078999508:android:c0a20986b3261fe0935641',
    messagingSenderId: '725078999508',
    projectId: 'fixitapp-a6733',
    storageBucket: 'fixitapp-a6733.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlQkN8GtL5oJTQIiUMvQIPEE0zV39bP3c',
    appId: '1:725078999508:ios:354a96978ff2eaae935641',
    messagingSenderId: '725078999508',
    projectId: 'fixitapp-a6733',
    storageBucket: 'fixitapp-a6733.firebasestorage.app',
    iosClientId: '725078999508-pikhtjcgrq6c74nr009bc27gdjvh18n2.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlQkN8GtL5oJTQIiUMvQIPEE0zV39bP3c',
    appId: '1:725078999508:ios:354a96978ff2eaae935641',
    messagingSenderId: '725078999508',
    projectId: 'fixitapp-a6733',
    storageBucket: 'fixitapp-a6733.firebasestorage.app',
    iosClientId: '725078999508-pikhtjcgrq6c74nr009bc27gdjvh18n2.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBierfXGriDzTYB61VEgYjC7o991hi3uds',
    appId: '1:725078999508:web:4d8ccbeea04d2c84935641',
    messagingSenderId: '725078999508',
    projectId: 'fixitapp-a6733',
    authDomain: 'fixitapp-a6733.firebaseapp.com',
    storageBucket: 'fixitapp-a6733.firebasestorage.app',
    measurementId: 'G-6PDN16782Z',
  );

}